title: Eldritch Gambit
logo: "/images/Logo.png"
email: zhongjake@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  System Reference Document, Press Kit, and Frequently Asked Questions about
  METTLE Core, a pulp adventure RPG by Jake Eldritch of Planarian Games.
baseurl: "/eldritchgambit" # the subpath of your site, e.g. /blog
url: "https://Planarian.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PlanarianGames
github_username:  PlanarianGames

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Callouts
callouts:
  highlight:
    title: TL;DR
    color: yellow
  outcomes:
    title: Outcomes
    color: blue
  note:
    title: Note
    color: red


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
